sudo: false
language: node_js
node_js:
  - "stable"
env:
  global:
    - secure: "io5woqNiPeOlqVArkmWa8qDFxYfFgSRtQxuAER+a8x8KQk7Gle7/kdg8dq4JBiqzL38JrT2Q+ofqHvxigdJPByl2dWcuSI8gE2JPqS3FfOVithYWmZS11DMQFXC58H7S4wXsHwFzUEAy06jzQwGRA3BXkSD4SNiknDG0FmAyM1tJsR7iCIAsH3zoS+ZpS+tSn9M1qwObLQYhNURFWCcttqOddhw7pbFalcpEfzvDuf258eiSdQUxzucJBJ9MDwTT9nncqRA/fiq5/K3CTvtI4xU/H1xPasqJBXRwDqPm/QvaNKYkiIhk0aymnLejgDk+mz/8WPAFb6IPCrvx2kU2DRdNdfELKCTNY2i56ACPpzIoXkzpTMB3OxObt93zX+U/ldbmEXWAu9NByxJ5Q8BM4iCmG4yRJTa3evFmbYauJUaudFlnPGjtw9hsfwFblmdbcgyJ4mgENYSN3ebJb2Hytj316PLsSYH9mrB/Wi/qvEB+nR2Qy94zwGo76QuEWeO5vvn35rTFvGWkj1VPwo+Hs2GC3xm0kKx047l7ELQVSGCnwfDAbXb/QbSaX0+LbqIyGC5MXVfeSStihxNpFcpcaiRjkW7yTZvTHZduUa/jq/mdEAceXxQm7N6soQkOI1jlW3TOYYu+/6x3KXHzjFhtdVXygiwN6x2DEBDkcekyCb4="
after_success:
  - $(npm bin)/coveralls < ./coverage/lcov.info
